# Generated by Django 4.2.16 on 2026-04-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wnet_id', models.CharField(max_length=50, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=300)),
                ('work_region', models.CharField(max_length=100)),
                ('wage', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('detail_url', models.URLField(blank=True)),
            ],
        ),
    ]
