# Generated by Django 4.2.16 on 2026-04-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentSupportCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='권역 (예: 서울, 경기/인천 등)', max_length=50)),
                ('name', models.CharField(help_text='센터명', max_length=100)),
                ('location', models.CharField(help_text='상세 지역', max_length=200)),
                ('phone_number', models.CharField(help_text='연락처', max_length=50)),
            ],
        ),
    ]
