# Generated by Django 4.2.16 on 2026-04-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PensionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('company_name', models.CharField(max_length=200)),
                ('total_amount', models.CharField(blank=True, max_length=50)),
                ('client_org', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
